### ISSUE TITLE
from visual_create.html sub categories are not being inserted into the database

### ISSUE THREAD

**Issue by Franco-Henriquez** [deconoixggabell/Brainstorm_visualizer#8]
The main idea and categories are created successfully in the database. The sub-categories are not, no errors in the log. Possible controller instruction or form instruction missing.

![image](https://github.com/deconoixggabell/Brainstorm_visualizer/assets/124027108/8504d66a-134a-4af5-8ca9-65643a8b3382)

**Comment by springsteenptrck** [comment]
Issue with naming convention. Fix complete #12
